name: Meschichi

channels:
  - conda-forge
  - pytorch
  - nvidia

dependencies:
  - python=3.10
  - numpy=1.23
  - scipy
  - scikit-image
  - pandas
  - opencv
  - joblib
  - matplotlib-base=3.6
  - nd2
  - pytorch
  - pytorch-cuda=11.7
  - pip
  - pip:
    - cellpose[gui]
    - albumentations
    - napari[all]
    - spyder